(deftheme Doughlaff
  "Created 2018-06-24.")

(custom-theme-set-variables
 'Doughlaff
 '(show-paren-mode t)
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(backup-by-copying-when-linked t)
 '(backup-directory-alist (quote (("." . "~/.emacs.d/backups"))))
 '(custom-safe-themes (quote ("d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" default)))
 '(delete-old-versions t)
 '(dired-listing-switches "-lh")
 '(erc-fill-column 125)
 '(erc-hide-timestamps t)
 '(erc-prompt ">")
 '(eshell-cmpl-cycle-completions nil)
 '(focus-follows-mouse t)
 '(ido-mode (quote both))
 '(initial-buffer-choice "~/")
 '(kept-new-versions 6)
 '(kept-old-versions 3)
 '(mouse-autoselect-window t)
 '(nyan-animate-nyancat t)
 '(scroll-bar-mode nil)
 '(version-control t)
 '(erc-fill-mode nil)
 '(erc-stamp-mode t)
 '(erc-track-mode nil)
 '(fringe-mode (quote (1 . 1)))
 '(menu-bar-mode nil)
 '(tool-bar-mode nil)
 '(tramp-mode t)
 '(nyan-mode nil)
 '(nyan-wavy-trail nil)
 '(package-selected-packages (quote (conkeror-minor-mode cpputils-cmake disaster flymake-cppcheck format-all function-args google-c-style lua-mode helm flylisp fennel-mode sudo-edit nyan-mode rainbow-mode solarized-theme)))
 '(helm-mode t))

(custom-theme-set-faces
 'Doughlaff
 '(erc-default-face ((t (:foreground "#1e79a1" :weight bold))))
 '(erc-notice-face ((t (:foreground "gray" :height 0.75))))
 '(mode-line-highlight ((t (:foreground "cyan" :weight bold))))
 '(eshell-prompt ((t (:foreground "#1e7990" :weight bold))))
 '(default ((t (:inherit nil :stipple nil :background "#fdf6e3" :foreground "dark slate gray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 151 :width normal :foundry "Bits" :family "Bitstream Vera Sans Mono"))))
 '(show-paren-match ((t (:foreground "dodger blue" :weight bold))))
 '(mode-line ((t (:background "#1e7990" :foreground "#0fafaf"))))
 '(mode-line-inactive ((t (:background "#1e7990" :foreground "#af7aa0"))))
 '(mode-line-buffer-id ((t (:foreground "#ffffaf"))))
 '(info-xref ((t (:foreground "light sea green")))))

(provide-theme 'Doughlaff)
